stages:
  - check
  - test

check-code:
  stage: check
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/check_java.sh\""
  
test-code-8:
  stage: test
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_8.sh\""
  
test-code-11:
  stage: test
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_11.sh\""
  
test-code-17:
  stage: test
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_17.sh\""
